### PR TITLE
Update `hoek` reference to version 5.0.3

### PR DESCRIPTION
**Pull request by carlos-enciso**

### CODE REVIEW

**Review by ccavazos — APPROVED** [review]
I assume this was somehow tested just to make sure nothing gets broken.

**Comment by carlos-enciso** [comment]
tested uploading OTHC DEV ipa with success

**Comment by ccavazos** [comment]
Great, thanks!

**Comment by pablog178** [comment]
@carlos-enciso did you updated it by hand, or by running `npm install` again?

**Comment by carlos-enciso** [comment]
both, tried by hand, then ran `npm install`,  the version of `hoek` found was indeed 5.0.3 and not the old one

**Review by pablog178 — APPROVED** [review]

**Pull request merged**
